server:
    logrus: 
        json: false
        level: "debug"
    address: "localhost:9999"

db:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"